fix: update coverage processing to include SQLite database checks and streamline result handling

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -86,24 +86,22 @@ jobs:
         run: poetry install --no-interaction
       - name: Debug - Check coverage version
         run: poetry run coverage --version
-      - name: Convert and reprocess coverage data
+      - name: Debug SQLite database
         run: |
-          poetry run coverage json
-          poetry run coverage combine coverage.json
-          poetry run coverage xml -i
-          poetry run coverage report
-    #   - name: 🚀 Process coverage results
-    #     run: |
-    #       if [ -f ".coverage" ]; then
-    #         echo "Coverage file exists"
-    #         ls -l .coverage
-    #         poetry run coverage combine --append .coverage
-    #         poetry run coverage xml -i
-    #         poetry run coverage report
-    #       else
-    #         echo ".coverage file not found"
-    #         exit 1
-    #       fi
+          echo ".tables" | sqlite3 .coverage
+          echo "SELECT * FROM coverage_schema;" | sqlite3 .coverage
+      - name: 🚀 Process coverage results
+        run: |
+          if [ -f ".coverage" ]; then
+            echo "Coverage file exists"
+            ls -l .coverage
+            poetry run coverage combine --append .coverage
+            poetry run coverage xml -i
+            poetry run coverage report
+          else
+            echo ".coverage file not found"
+            exit 1
+          fi
       - name: 🚀 Upload coverage report
         uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
         with:
